### ISSUE TITLE
New Account Creation

### ISSUE THREAD

**Issue by wreardan** [ckumar1/smart-fridge-android#19] opened 2014-05-02 16:12 UTC
When opening the App for the first time I first received the login screen and I tried to 'login' but you have to 'register' first. I was confused and didn't see the small register link so I ended up having to enter in my login/register information twice.

**Comment by wreardan** [comment] 2014-05-02 16:15
It would also be nice if the app could remember your email address or stayed permanently logged in so you don't have to log in with email/password each time you use the application.

**Comment by carlpratt** [comment] 2014-05-02 16:27
I'm a little confused by this because our login / register functionality doesn't do anything yet, so you shouldn't have to input your email/password to begin with. You need only hit login to be taken to the main application.

In terms of keeping a user logged in, we already do this. Once a user logs in, if they close the app and reopen it they will not have to log in again. Can you describe the steps you took to get to the main activity where you were not logged in again after reopening the app?

**Comment by wreardan** [comment] 2014-05-02 16:34
Oh, I did not realize that you could just press login with empty credentials to bypass that screen.  I was logging in every time (maybe it wasn't actually doing anything).  I'm going to be grocery shopping in a little bit for a test run.

**Comment by corypgr** [comment] 2014-05-02 20:18
Main issue, that register and Login do not work, is a duplicate of issue #16

**Closed as completed** 2014-05-06 20:32 UTC
Labels: duplicate, CS638-TestAssignment
