### ISSUE TITLE
Barcode scanning causes app to crash

### ISSUE THREAD

**Issue by jaltekruse** [ckumar1/smart-fridge-android#28] opened 2014-05-02 20:21 UTC
I assume it is because it is unimplimented, but it might be because I don't have a bar code scanner set up right and the app isn't handling the failure. Interestingly it doesn't bring me back to the home screen, it seems to only crash the current activity and bring me back to the food list.

**Comment by corypgr** [comment] 2014-05-02 20:24
Duplicate of issue #20 
This does appear to be because you do not have a barcode scanner installed. We'll have to check for that.

**Closed as completed** 2014-05-06 20:31 UTC
Labels: duplicate, CS638-TestAssignment
